title: Elug CE
email: elugce@gmail.com
description: Grupo de usuários Elixir/Erlang do Ceará
baseurl: ""
url: ""

collections:
  meetups:
    output: true

facebook_username: elugce
github_username: elug-ce
instagram_username: elug_ce
twitter_username: elug_ce

disqus:
  shortname: elug-ce
google_analytics: UA-166036246-1

# Build settings
future: true
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
